### ISSUE TITLE
关于预测结果的一个疑问

### ISSUE THREAD

**Issue by yyb1995** [lijincheng718/Mechine-Learning-Forecasting#1]
您好，首先十分感谢您上传的时序预测工程。我在运行LSTM_stack和DNN这两种预测方法后，把结果图形放大了一下，发现预测值和真实值之间存在一个时间单位的偏差，就是预测值要滞后于真实值一个时间单位。就好像是神经网络只学到了让输出等于最后一个输入。我最近也在做LSTM时间预测的问题，也是遇到了这种情况。我上网查了，发现好多人也有类似的结果。想请教您一下是否了解出现这种情况的原因，以及这是否属于可以接受的预测结果，谢谢！

**Comment by jujubbgg** [comment]
> 我在运行LSTM_stack和DNN这两种预测方法后，把结果图形放大了一下，发现预测值和真实值之间存在一个时间单位的偏差，就是预测值就是滞后于真实值一个时间单位。就好像是神经网络只学到了让输出等于最后一个输入。我最近同时做LSTM时间预测的问题，也是遇到了这种情况。我上网查了，发现好多人也有类似的结果。想请教您一下是否了解出现这种情况的原因，以及这是否可以接受的预测结果，谢谢！

你好，我的python是3.6，文件夹中的EMD.py是python2写的吗？我运行报错如下
Traceback (most recent call last):
  File "C:/Users/mi/Desktop/Mechine-Learning-Forecasting-master/BearingCapacity/EMD.py", line 23, in <module>
    IMF = EMD().emd(s)
  File "C:\Users\mi\Anaconda3\lib\site-packages\emd_signal-0.2.7-py3.6.egg\PyEMD\EMD.py", line 775, in emd
TypeError: unsupported operand type(s) for -: 'str' and 'float'
